// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import StimulusController from "./stimulus_controller"
application.register("stimulus", StimulusController)

import SourceToggleController from "./source_toggle_controller"
application.register("source-toggle", SourceToggleController)

import DarkModeController from "./dark_mode_controller"
application.register("dark-mode", DarkModeController)

import FavoritesController from "./favorites_controller"
application.register("favorites", FavoritesController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import AvatarCropperController from "./avatar_cropper_controller"
application.register("avatar-cropper", AvatarCropperController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)
