// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import StimulusController from "./stimulus_controller"
application.register("stimulus", StimulusController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import DarkModeController from "./dark_mode_controller"
application.register("dark-mode", DarkModeController)

import FavoritesController from "./favorites_controller"
application.register("favorites", FavoritesController)
